- name: Deploy FastAPI CRUD App on EC2
  hosts: all
  become: true
  tasks:
    - name: Run FastAPI container
      docker_container:
        name: fastapi-app
        image: nikchand/fastapi-crud:latest
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
